# Generated by Django 3.1 on 2021-05-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='name',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
